targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"
      freezed|freezed:
        enabled: true
      json_serializable:
        enabled: true
        options:
          explicit_to_json: true
          field_rename: snake
